theme: jekyll-theme-cayman

<iframe src="/Users/bd7717/Desktop/02806SocialDataAnalysisandVisualization/Finalproject/cons.html"
    sandbox="allow-same-origin allow-scripts"
    width="100%"
    height="500"
    scrolling="no"
    seamless="seamless"
    frameborder="0">
</iframe>

<iframe src="cons.html"
    sandbox="allow-same-origin allow-scripts"
    width="100%"
    height="500"
    scrolling="no"
    seamless="seamless"
    frameborder="0">
</iframe>

{% include /custom//Users/bd7717/Desktop/02806SocialDataAnalysisandVisualization/Finalproject/cons.html %}

{% include /custom/cons.html %}

<div></div>